services:
  # seerr:
  #   container_name: seerr
  #   image: ghcr.io/seerr-team/seerr:v3.0.1
  #   init: true
  #   environment:
  #     - TZ=Asia/Tokyo
  #   ports:
  #     - 5055:5055/tcp
  #   volumes:
  #     - /opt/docker/seerr:/app/config
  #   restart: unless-stopped
  #   healthcheck:
  #     test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
  #     start_period: 20s
  #     timeout: 3s
  #     interval: 15s
  #     retries: 3

  requestrr:
    container_name: requestrr
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 4545:4545/tcp
    volumes:
      - /opt/docker/requestrr:/root/config
    restart: unless-stopped
    image: thomst08/requestrr:v2.1.9

    overseerr:
      container_name: overseerr
      environment:
        - TZ=Asia/Tokyo
        - PUID=99
        - PGID=100
        - UMASK=022
      ports:
        - 5055:5055/tcp
      volumes:
        - /opt/docker/overseerr:/config
      restart: unless-stopped
      image: lscr.io/linuxserver/overseerr:1.35.0