services:
  headscale:
    container_name: headscale
    image: headscale/headscale:0.29.3
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "3478:3478/udp" # DERP/STUN
    volumes:
      - ${PODMAN_DATA}/headscale/config:/etc/headscale:Z
      - ${PODMAN_DATA}/headscale/data:/var/lib/headscale:Z
      - ${PODMAN_DATA}/certs:/etc/headscale/certs:z,ro
    entrypoint: headscale serve
    labels:
      me.tale.headplane.target: headscale

  headplane:
    image: ghcr.io/tale/headplane:0.7.0
    container_name: headplane
    restart: unless-stopped
    ports:
      - "3001:3001"
    security_opt:
      - label=disable
    volumes:
      - ${PODMAN_DATA}/headplane/config/config.yaml:/etc/headplane/config.yaml:Z
      - ${PODMAN_DATA}/headscale/config/config.yaml:/etc/headscale/config.yaml:z
      - ${PODMAN_DATA}/headplane/data:/var/lib/headplane:Z
      - ${PODMAN_DATA}/headscale/data:/var/lib/headscale:z
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock
    depends_on:
      - headscale

networks:
 default:
   driver: bridge
   enable_ipv6: true
