services:
  whoami:
    image: traefik/whoami:v1.11.0
    container_name: whoami
    ports:
      - 2080:80
    # command:
    #   # It tells whoami to start listening on 2001 instead of 80
    #   - --port=2001
    #   - --name=iamfoo

  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    environment:
      MODE: standalone
      #TITLE: "LibreSpeed"
      #TELEMETRY: "false"
      #ENABLE_ID_OBFUSCATION: "false"
      #REDACT_IP_ADDRESSES: "false"
      #PASSWORD:
      #EMAIL:
      #DISABLE_IPINFO: "false"
      #IPINFO_APIKEY: "your api key"
      #DISTANCE: "km"
      #WEBPORT: 8080
    ports:
      - "2081:8080" # webport mapping (host:container)

  caddy:
    image: ghcr.io/tsuki-tsuki/caddy:2.10.2
    container_name: caddy
    restart: unless-stopped
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "443:443/udp"
    volumes:
      - ${PODMAN_DATA}/caddy/config:/etc/caddy
      - ${PODMAN_DATA}/caddy/site:/srv
      - ${PODMAN_DATA}/caddy/data:/data
      - ${PODMAN_DATA}/caddy/run:/config
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:ro
      - ${PODMAN_DATA}/with_secrets.sh:/with-secrets.sh:ro
    secrets:
      - CF_API_TOKEN
    network_mode: "host"
    # networks:
    #   headscale-net: {}
    command: ["/with-secrets.sh", "caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]

networks:
 default:
   driver: bridge
   enable_ipv6: true

secrets:
  CF_API_TOKEN:
    file: ${PODMAN_DATA}/.secrets/cf_api_token
